### ISSUE TITLE
Reorder the tasks so you can skip moving the audio

### ISSUE THREAD

**Issue by benfoley** [CoEDL/kaldi-helpers#28]
When rebuilding, the move audio task has to rerun each time. Can we make a rebuild text task that can leave audio where it is?

**Comment by fauxneticien** [comment]
Hm but the `clean-output-folder` wipes everything out

```yaml
clean-output-folder:
  desc: "Delete all files and folders inside output directory"
  cmds:
    - rm -rf {{ .OUTPUT_PATH }}/*
```

Suggest splitting into 2 tasks. Default only wipes out non-audio data, and then another task `clean-all` can wipe all out.
